CREATE DATABASE quickvisionBD

USE quickvisionBD

CREATE TABLE UNIDADE_HAB(
BLOCO_NUMERO INT PRIMARY KEY)
--NUMERO_RES INT NOT NULL)

CREATE TABLE VEICULO(
ID_VEICULO INT PRIMARY KEY,
MODELO_VEICULO VARCHAR (20) NOT NULL,
PLACA_VEICULO VARCHAR (8) NOT NULL,
ANO_VEICULO CHAR (4) NOT NULL,
COR_VEICULO VARCHAR (10) NOT NULL)

CREATE TABLE MORADOR(
ID_MORADOR INT NOT NULL PRIMARY KEY IDENTITY,
NOME_MORADOR VARCHAR (50) NOT NULL,
CPF_MORADOR CHAR (11) NOT NULL,
TELEFONE_MORADOR CHAR (11) NOT NULL,
EMAIL_MORADOR VARCHAR (50),
BLOCO_NUMERO INT NOT NULL REFERENCES UNIDADE_HAB)
CREATE TABLE PORTEIRO(
ID_PORTEIRO INT PRIMARY KEY NOT NULL,
NOME_PORTEIRO VARCHAR (50) NOT NULL,
RG_PORTEIRO CHAR (10) NOT NULL)

CREATE TABLE PASSAGEM_MORADOR(
ID_EVENTO_TERC INT PRIMARY KEY IDENTITY,
DATA_PASSAGEM_TERC DATETIME NOT NULL,
ID_MORADOR INT NOT NULL REFERENCES MORADOR,
ID_PORTEIRO INT NOT NULL REFERENCES PORTEIRO)

CREATE TABLE VEICULO_MORADOR(
ID_VEICULO_MORADOR INT PRIMARY KEY IDENTITY,
ID_MORADOR INT NOT NULL REFERENCES MORADOR,
ID_VEICULO INT NOT NULL REFERENCES VEICULO,
UNIQUE (ID_MORADOR, ID_VEICULO))

CREATE TABLE VISITANTE(
ID_VISITANTE INT PRIMARY KEY IDENTITY,
NOME_VISITANTE VARCHAR (50) NOT NULL,
CPF_VISITANTE CHAR (11) NOT NULL,
TELEFONE_VISITANTE CHAR (11),
EMAIL_VISITANTE VARCHAR (50),
NOME_RESP_ESTADIA_VISIT VARCHAR (50) NOT NULL)

CREATE TABLE PASSAGEM_VISITANTE(
ID_EVENTO_VISIT INT PRIMARY KEY IDENTITY,
DATA_PASSAGEM_VISIT DATETIME NOT NULL,
ID_VISITANTE INT NOT NULL REFERENCES VISITANTE,
ID_PORTEIRO INT NOT NULL REFERENCES PORTEIRO)

CREATE TABLE VEICULO_VISITANTE(
ID_VEICULO_VISITANTE INT PRIMARY KEY IDENTITY,
ID_VISITANTE INT NOT NULL REFERENCES VISITANTE,
ID_VEICULO INT NOT NULL REFERENCES VEICULO,
UNIQUE (ID_VISITANTE, ID_VEICULO))

CREATE TABLE TERCEIRO(
ID_TERCEIRO INT PRIMARY KEY IDENTITY,
NOME_TERCEIRO VARCHAR (50) NOT NULL,
CNPJ_TERCEIRO CHAR (14) NOT NULL,
CPF_TERCEIRO CHAR (11),
RG_TERCEIRO CHAR (10),
CEP_TERCEIRO CHAR (8) NOT NULL,
ENDERECO_TERCEIRO VARCHAR (50),
TELEFONE_TERCEIRO CHAR (11) NOT NULL,
NOME_SOLICIT_SERVICO VARCHAR (50) NOT NULL)

CREATE TABLE PASSAGEM_TERCEIRO(
ID_EVENTO_TERC INT PRIMARY KEY IDENTITY,
DATA_PASSAGEM_TERC DATETIME NOT NULL,
ID_TERCEIRO INT NOT NULL REFERENCES TERCEIRO,
ID_PORTEIRO INT NOT NULL REFERENCES PORTEIRO)

CREATE TABLE VEICULO_TERCEIRO(
ID_VEICULO_TERCEIRO INT PRIMARY KEY IDENTITY,
ID_TERCEIRO INT NOT NULL REFERENCES TERCEIRO,
ID_VEICULO INT NOT NULL REFERENCES VEICULO,
UNIQUE (ID_TERCEIRO, ID_VEICULO))